### ISSUE TITLE
Crash in Length Distribution when file contains no sequences

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/FastQC#22]
`Started analysis of 19755_PCR.qualtrim.clean.fastq.gz
Analysis complete for 19755_PCR.qualtrim.clean.fastq.gz
Failed to process file 19755_PCR.qualtrim.clean.fastq.gz
java.lang.ArrayIndexOutOfBoundsException: -1
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.calculateDis
tribution(SequenceLengthDistribution.java:101)
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.raisesError(
SequenceLengthDistribution.java:190)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLRepo
rtArchive.java:336)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchi
ve.java:84)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(Offline
Runner.java:178)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java
:110)
        at java.lang.Thread.run(Thread.java:748)`

_Originally posted by @grendon in https://github.com/s-andrews/FastQC/issues/8#issuecomment-439933981_

**Comment by s-andrews** [comment]
Looking at the code which generates this I think this only gets triggered if the file we're analysing has no valid sequences in it.  In fact I just tried opening a blank file in fastqc and get the same crash:

```
Exception in thread "Thread-4" java.lang.ArrayIndexOutOfBoundsException: -1
	at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.calculateDistribution(SequenceLengthDistribution.java:101)
	at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.getResultsPanel(SequenceLengthDistribution.java:42)
	at uk.ac.babraham.FastQC.Results.ResultsPanel.analysisComplete(ResultsPanel.java:128)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
	at java.lang.Thread.run(Unknown Source)
```

We shouldn't be crashing under these circumstances though, so we need to handle this better, but I suspect that this is the root cause of this issue.  Can you please check the file from your original report and confirm whether there are any sequences in it.  It's possible that there is data there and it's being rejected for other reasons, but a blank file seems the most likely culprit.

**Comment by s-andrews** [comment]
No worries, this is definitely poor behaviour on the part of FastQC, so thanks for bringing it to our attention.

**Comment by madkinsz** [comment]
Hi! Wondering if this is being worked on at all or if there is a clear way to contribute. This is breaking one of my pipelines.

**Comment by s-andrews** [comment]
Sorry, this should have been closed ages ago.  It was fixed in 90d304e and the fix was in the 0.11.8 release.  If you update to that version then this shouldn't be an issue. 

If you're getting a crash with 0.11.8 can you please open a new bug and including the stack trace you get.  Thanks.

**Comment by madkinsz** [comment]
We were on an old version but just bumped to 0.11.8, I think it's likely we saw this behavior on 0.11.5. I'll get back to you if it's in 0.11.8.

**Comment by madkinsz** [comment]
It breaks making reports on an empty file.


```
Failed to process file SCRUBBED_SAMPLE_NAME_R1.fastq
java.lang.ArrayIndexOutOfBoundsException: -1
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.calculateDistribution(SequenceLengthDistribution.java:101)
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.raisesError(SequenceLengthDistribution.java:190)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:336)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
        at java.lang.Thread.run(Thread.java:748)
Failed to process file SCRUBBED_SAMPLE_NAME_R2.fastq
java.lang.ArrayIndexOutOfBoundsException: -1
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.calculateDistribution(SequenceLengthDistribution.java:101)
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.raisesError(SequenceLengthDistribution.java:190)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:336)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
        at java.lang.Thread.run(Thread.java:748)
[ec2-user@ip-IP run]$ cat ./work/aa/8cffddbf5cd288391bbc9bb57bc49b/SCRUBBED_SAMPLE_NAME_R1.fastq
[ec2-user@ip-IP run]$ fastqc --version
FastQC v0.11.8a
```

**Comment by s-andrews** [comment]
Ah, sorry.  It was fixed in f832ee7 but that never made it into a release.

Can you try the snapshot at:

https://www.bioinformatics.babraham.ac.uk/projects/fastqc/FastQC_v0.11.9.devel.zip

..and check that that works.  I'll have to push a new release to add this and a couple of other minor fixes.

**Comment by lebovic** [comment]
@madkinsz was this resolved? We're running into it now (still on v0.11.8)

**Comment by madkinsz** [comment]
Sorry about the delayed replied. Thanks for the ping @lebovic. This release (11.9.devel) allows processing of empty fastqs without error.

**Comment by madkinsz** [comment]
However, the report then appears to contain bad metadata that breaks our parsing later on

```
##FastQC        0.11.9.devel
>>Basic Statistics      pass
#Measure        Value
Filename        null
File type       null
```

**Comment by s-andrews** [comment]
The lack of a file type is fair enough since we have no data from which to infer it, but the lack of the file name is a bug.  Since this is a separate issue I've opened a new bug at #43

**Comment by madkinsz** [comment]
> The lack of a file type is fair enough since we have no data from which to infer it, but the lack of the file name is a bug. Since this is a separate issue I've opened a new bug at #43
Great! Thanks for being so responsive.

**Comment by s-andrews** [comment]
This should now all be fixed and I'll push this in the next release.
