### ISSUE TITLE
Out of Memory issue with BAM files

### ISSUE THREAD

**Issue by MalhotraAnkit** [s-andrews/FastQC#24]
Getting the following error on a merged oxford nanopore based BAM file. Suggestions ?

Exception in thread "Thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at uk.ac.babraham.FastQC.Modules.GCModel.GCModel.<init>(GCModel.java:69)
        at uk.ac.babraham.FastQC.Modules.PerSequenceGCContent.processSequence(PerSequenceGCContent.java:198)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:88)
        at java.lang.Thread.run(Thread.java:745)

**Comment by bioXiaoheng** [comment]
How big is your memory?

**Comment by s-andrews** [comment]
For memory issues (and nanopore can certainly trigger these if you have some very long reads) then you can try adding ```-t 2``` (or even higher than 2) to force a higher memory allocation in fastqc.
