### ISSUE TITLE
"tile" module causes various memory exceptions

### ISSUE THREAD

**Issue by ryanrichholt** [s-andrews/FastQC#25]
We have a recent sequencing run from our Novaseq, R1/R2 fastq files from multiple lanes, that are running into errors with v0.11.8. It looks like one of the threads crashes, but the main thread hangs indefinitely. Other files from the same run complete fine:

```
Exception in thread "Thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.String.toCharArray(String.java:2899)
	at uk.ac.babraham.FastQC.Modules.NContent.processSequence(NContent.java:90)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:88)
	at java.lang.Thread.run(Thread.java:745)
```

```
Exception in thread "Thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.lang.String.replaceFirst(String.java:2178)
```

```
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
	at uk.ac.babraham.FastQC.Utilities.QualityCount.<init>(QualityCount.java:33)
	at uk.ac.babraham.FastQC.Modules.PerTileQualityScores.processSequence(PerTileQualityScores.java:281)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:88)
	at java.lang.Thread.run(Thread.java:745)
```

- We found that it completes fine if we disable the "tile" module.
- The files that failed all seem to be relatively low reads compared to the others from this run.

**Comment by ryanrichholt** [comment]
Here are some example fastqs that were failing: https://drive.google.com/drive/folders/1jbMS5ZOal8nrI7OcNLc4SGqovgsIjea4?usp=sharing

**Comment by s-andrews** [comment]
Sorry, I've just seen a bunch of issues which were opened - none of the notifications made it to me for some reason.

I just tried your files on my local version and they all processed just fine so I'm not sure why they were failing.  The crash is a GC limit which sounds like it's getting too close to running out of memory.  Can you try running one of the files with ```-t 2``` as an additional option and see if that fixes things on your system.

**Comment by ryanrichholt** [comment]
It's been quite a while, and I can no longer replicate the issue so closing for now. Thanks for replying!
