### ISSUE TITLE
after install fastqc,have some err information

### ISSUE THREAD

**Issue by chaimol** [s-andrews/FastQC#32]
when i download and unzip FastQC V0.11.8 ,
run`fastqc` it console this err message
`Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at uk.ac.babraham.FastQC.FastQCApplication.<init>(FastQCApplication.java:63)
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:332)
`
my java information is
`
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

`
i need you help on how to solve it?i do not have the Administrator privileges。

**Comment by bny6613** [comment]
Did you run it without any arguments? By default (if no arguments provided) it runs in GUI mode, Run ```fastqc --help```

**Comment by chaimol** [comment]
> 你没有任何争论地运行它吗？默认情况下（如果没有提供参数）它在GUI模式下运行，运行`fastqc --help`



> Did you run it without any arguments? By default (if no arguments provided) it runs in GUI mode, Run `fastqc --help`

Thank you. I have solve this problem. I do not install GUI ,so in default it have this info. As long as I enter the complete command, it will work properly.
