### ISSUE TITLE
Exit with non-zero exit status on SequenceFormatException

### ISSUE THREAD

**Issue by nathanweeks** [s-andrews/FastQC#45]
When fastqc 0.11.9 encounters a truncated FASTQ file, it still exits with an exit status of 0:
```
$ fastqc -o ../QC-test/ ./TC4-120-H-10X/TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Started analysis of TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 5% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 10% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 15% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 20% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 25% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 30% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 35% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 40% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 45% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 50% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 55% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 60% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 65% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 70% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 75% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 80% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 85% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 90% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Approx 95% complete for TC4-120-H-10X_S038_L003_R2_001.fastq.gz
Failed to process file TC4-120-H-10X_S038_L003_R2_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Ran out of data in the middle of a fastq entry.  Your file is probably truncated
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:179)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:77)
        at java.base/java.lang.Thread.run(Thread.java:834)
$ echo $?
0

```
 It would be highly-preferable for fastqc to exit with a non-zero exit status, particularly when used in pipelines where stderr isn't necessarily inspected unless an error is otherwise detected (typically via a non-zero exit status of a command).

**Comment by nathanweeks** [comment]
FWIW, we encountered a (BGZF-formatted) .fastq.gz file that had a corrupt BGZF block early on in the file:

```
Singularity> fastqc -o /tmp C3-poly_S10_L001_R1_001.fastq.gz
Started analysis of C3-poly_S10_L001_R1_001.fastq.gz
Approx 5% complete for C3-poly_S10_L001_R1_001.fastq.gz
java.util.zip.ZipException: Not in GZIP format
        at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
        at uk.ac.babraham.FastQC.Utilities.MultiMemberGZIPInputStream.<init>(MultiMemberGZIPInputStream.java:43)
        at uk.ac.babraham.FastQC.Utilities.MultiMemberGZIPInputStream.read(MultiMemberGZIPInputStream.java:103)
        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:138)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:77)
        at java.base/java.lang.Thread.run(Thread.java:834)
Analysis complete for C3-poly_S10_L001_R1_001.fastq.gz
Hide quoted text
Singularity> echo $?
0
```
FastQC still produced .html and .zip files for the reads it was able to process (which is OK), but then exited with an exit status of 0, so this error was undetected in our sequence processing pipeline (an end user alerted us when they were unable to use cutadapt on the corrupt .fastq.gz file).

**Comment by s-andrews** [comment]
I've had a look at this and I can only partially replicate it.  I do get a zero exit status which is weird as the exception is triggered so it should spot that.  I don't however get a report file generated.

```
[andrewss@headstone ~]$ ls truncated*
truncated.fastq.gz
[andrewss@headstone ~]$ fastqc truncated.fastq.gz
Started analysis of truncated.fastq.gz
Approx 5% complete for truncated.fastq.gz
Approx 10% complete for truncated.fastq.gz
Approx 15% complete for truncated.fastq.gz
Approx 20% complete for truncated.fastq.gz
Approx 30% complete for truncated.fastq.gz
Approx 35% complete for truncated.fastq.gz
Approx 40% complete for truncated.fastq.gz
Approx 45% complete for truncated.fastq.gz
Approx 55% complete for truncated.fastq.gz
Approx 60% complete for truncated.fastq.gz
Approx 65% complete for truncated.fastq.gz
Approx 70% complete for truncated.fastq.gz
Approx 75% complete for truncated.fastq.gz
Approx 85% complete for truncated.fastq.gz
Approx 90% complete for truncated.fastq.gz
Approx 95% complete for truncated.fastq.gz
Failed to process file truncated.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Ran out of data in the middle of a fastq entry.  Your file is probably truncated
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:179)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:77)
        at java.base/java.lang.Thread.run(Unknown Source)
[andrewss@headstone ~]$ echo $?
0
[andrewss@headstone ~]$ ls truncated*
truncated.fastq.gz
[andrewss@headstone ~]$ fastqc --version
FastQC v0.11.9
```

I'll have to work out why the error is being trapped properly.

**Comment by nathanweeks** [comment]
Thanks! To clarify, the report file was generated in the second case: `java.util.zip.ZipException` that was raised upon encountering a corrupt BGZF block (`cellranger mkfastq` uses BGZF compression for some reason instead of vanilla gzip) in the middle of a large, otherwise-seemingly-complete .fastq.gz file? I don't recall if a report file was still generated when the `uk.ac.babraham.FastQC.Sequence.SequenceFormatException` was raised for the truncated file.

**Comment by nathanweeks** [comment]
To help reproduce/test, here's the FASTQ file with the corrupt BGZF block mentioned in https://github.com/s-andrews/FastQC/issues/45#issuecomment-589385566:

https://drive.google.com/a/harvard.edu/file/d/1bk1n1GtNUFiiCSRBwoFh4hbohPwYfa0M

It's ~2.35 GB in size.

**Comment by s-andrews** [comment]
I think I've found this.  We do check for failures, but the way the check is scoped it only detects failures when the filehandle is first set up (eg missing files), and doesn't spot the error when the analysis fails part way through.

I've added a patch which should catch these later failures as well.

**Comment by s-andrews** [comment]
This is a test with the fixed version:

```
[andrewss@headstone fastqc_dev]$ ./fastqc --version
FastQC v0.11.10.devel
[andrewss@headstone fastqc_dev]$ ./fastqc ../truncated.fastq.gz
Started analysis of truncated.fastq.gz
Approx 5% complete for truncated.fastq.gz
Approx 10% complete for truncated.fastq.gz
Approx 15% complete for truncated.fastq.gz
Approx 20% complete for truncated.fastq.gz
Approx 30% complete for truncated.fastq.gz
Approx 35% complete for truncated.fastq.gz
Approx 40% complete for truncated.fastq.gz
Approx 45% complete for truncated.fastq.gz
Approx 55% complete for truncated.fastq.gz
Approx 60% complete for truncated.fastq.gz
Approx 65% complete for truncated.fastq.gz
Approx 70% complete for truncated.fastq.gz
Approx 75% complete for truncated.fastq.gz
Approx 85% complete for truncated.fastq.gz
Approx 90% complete for truncated.fastq.gz
Approx 95% complete for truncated.fastq.gz
Failed to process file truncated.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Ran out of data in the middle of a fastq entry.  Your file is probably truncated
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:179)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:77)
        at java.lang.Thread.run(Thread.java:748)
[andrewss@headstone fastqc_dev]$ echo $?
1
```

**Comment by s-andrews** [comment]
You can try the fixed version using the development snapshot at:

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.10.devel.zip

**Comment by nathanweeks** [comment]
Thanks! However, I still see an exit status of 0 for the file with the corrupt BGZF block?
```
$ ../test/FastQC/fastqc --version 
FastQC v0.11.10.devel
$ ../test/FastQC/fastqc C3-poly_S10_L001_R1_001.fastq.gz
Started analysis of C3-poly_S10_L001_R1_001.fastq.gz
Approx 5% complete for C3-poly_S10_L001_R1_001.fastq.gz
java.util.zip.ZipException: Not in GZIP format
        at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
        at uk.ac.babraham.FastQC.Utilities.MultiMemberGZIPInputStream.<init>(MultiMemberGZIPInputStream.java:43)
        at uk.ac.babraham.FastQC.Utilities.MultiMemberGZIPInputStream.read(MultiMemberGZIPInputStream.java:103)
        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:138)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:77)
        at java.base/java.lang.Thread.run(Thread.java:844)
Analysis complete for C3-poly_S10_L001_R1_001.fastq.gz
$ echo $?
0
```

**Comment by s-andrews** [comment]
Something really weird is going on.  This should be being caught but isn't.

```
Started analysis of C3-poly_S10_L001_R1_001.fastq.gz
Approx 5% complete for C3-poly_S10_L001_R1_001.fastq.gz
java.util.zip.ZipException: Not in GZIP format
	at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
	at uk.ac.babraham.FastQC.Utilities.MultiMemberGZIPInputStream.<init>(MultiMemberGZIPInputStream.java:43)
	at uk.ac.babraham.FastQC.Utilities.MultiMemberGZIPInputStream.read(MultiMemberGZIPInputStream.java:103)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:138)
	at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:76)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

..but the ```uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:76)``` is the ```file.next()``` line in :

```
			try {
				seq = file.next();
			}
			catch (Exception e) {
				System.err.println("Caught an exception");
				i = listeners.iterator();
				while (i.hasNext()) {
					i.next().analysisExceptionReceived(file,e);
				}
				return;
			}
```

So it's in a try/catch block so it shouldn't just propagate up the stack but should be caught and handled.  I'm probably being thick but I can't see why it's not triggering the catch block.

ZipException is definitely a standard Exception:

https://docs.oracle.com/javase/7/docs/api/java/util/zip/ZipException.html

The only thing I can think of is whether the unzip process starts a new thread and that's how it escapes?  Seems like that would be documented though.

**Comment by s-andrews** [comment]
Found it!  There was a separate try/catch in the FastQFile class which was catching the IOException and wasn't turning it into a SequenceFormatException to pass up the stack.  That also explains why the report was being generated since it returned a null sequence which wouldn't cause the processing to stop.

**Comment by s-andrews** [comment]
It now seems to do the right thing...

```
[andrewss@headstone FastQC]$ ./fastqc ../C3-poly_S10_L001_R1_001.fastq.gz
Started analysis of C3-poly_S10_L001_R1_001.fastq.gz
Approx 5% complete for C3-poly_S10_L001_R1_001.fastq.gz
Failed to process file C3-poly_S10_L001_R1_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Not in GZIP format
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:214)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:77)
        at java.lang.Thread.run(Thread.java:748)
[andrewss@headstone FastQC]$ echo $?
1

```

**Comment by s-andrews** [comment]
I've updated the dev snapshot at 

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.10.devel.zip

..with the new fixes.  Can you please check this works for you.

**Comment by nathanweeks** [comment]
Yes, that works! In a test case with 64 .fastq.gz files (containing two .fastq.gz files with corrupt BGZF blocks):
```
$ ls *.fastq.gz | wc -l
64
$ ../test/FastQC/fastqc --threads=32 --out=out *.fastq.gz
...
Approx 5% complete for C4-poly_S11_L002_R1_001.fastq.gz
Failed to process file C4-poly_S11_L001_R2_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Not in GZIP format
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:214)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:77)
        at java.base/java.lang.Thread.run(Thread.java:844)
...
Failed to process file C3-poly_S10_L001_R1_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Not in GZIP format
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:214)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:77)
        at java.base/java.lang.Thread.run(Thread.java:844)
...
$ echo $?
1
$ ls out/*.zip | wc -l
62
$ ls out/*.html | wc -l
62
```
I don't still have the original truncated fastq.gz file mentioned at the beginning of the issue, but unless the code path for the exception is somehow substantially different in that case, I'll assume it also works (i.e., returns non-zero exit status) when `--threads` > 1.

Thank you!

**Comment by s-andrews** [comment]
Great.  Thanks for testing.  This will go out in the next release.

**Comment by AstrobioMike** [comment]
hiya, @s-andrews :)

Thanks for your maintenance work on fastqc!

Any chance you could update the release so this fix (and others) get into a release package? (this is essential for those of who use things like conda environments)

**Comment by s-andrews** [comment]
Yes, absolutely.  Sorry, the release is built but I need to borrow a mac to do some final testing and then I can push it.

**Comment by AstrobioMike** [comment]
Stellar, thanks!
