### ISSUE TITLE
where is the wrong when running fastQC?

### ISSUE THREAD

**Issue by decenwang** [s-andrews/FastQC#5]
Approx 65% complete for Normal_10_S4_L003_R1_001.fastq
Approx 75% complete for Normal_10_S4_L003_R1_001.fastq
Approx 80% complete for Normal_10_S4_L003_R1_001.fastq
Approx 90% complete for Normal_10_S4_L003_R1_001.fastq
Approx 95% complete for Normal_10_S4_L003_R1_001.fastq
Analysis complete for Normal_10_S4_L003_R1_001.fastq
_Failed to process file Normal_10_S4_L003_R1_001.fastq
java.lang.IllegalArgumentException: No key called gc_sequence:ignore in the config data
	**at uk.ac.babraham.FastQC.Modules.ModuleConfig.getParam(ModuleConfig.java:148)
	at uk.ac.babraham.FastQC.Modules.PerSequenceGCContent.ignoreInReport(PerSequenceGCContent.java:57)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:331)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:155)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
	at java.lang.Thread.run(Thread.java:748)**_

**Comment by lailinbin** [comment]
I have the same problem.I solve this problem as following:
copy the file named Configure in your fastqc path to /etc/fastqc
Note:you must get root right first if you cann't open etc file.

**Comment by s-andrews** [comment]
If anything is trying to read from /etc/ then you're not using the fastqc source which we distribute, it must be a patched version which a linux distribution has created.  Our fastqc version only ever tries to read it's configuration from the "Configuration" directory inside the program's own directory.
