### ISSUE TITLE
CRAM as input format?

### ISSUE THREAD

**Issue by FriederikeHanssen** [s-andrews/FastQC#54]
I was wondering whether `cram` is also an accepted input format. I can't get FastQc to run with it, but I was not sure whether the file is corrupted or whether FastQC just doesn't accept crams in general.

**Comment by s-andrews** [comment]
The current release doesn't support CRAM as we're still using the older samtools java library to read BAM files and that predates CRAM.

I think it would be easy enough to add support for this if we updated to use the HTSJDK library which replaced the old samtools one.  It's not a drop in replacement, but the changes are pretty minimal (I had to do this for seqmonk) and there is a speedup as a nice side effect.

The other issue with CRAM is going to be supporting the required reference genomes.  When we added support in seqmonk this wasn't an issue as we only needed the mapped positions, but in FastQC we need the sequences so we'll need the full reference genome.  This would either then require a way to manually specify the genome - which could be different for multiple CRAM files in the same run, or we could auto-download them, but that could be a pretty unfriendly experience if you end up downloading several gigs of reference before your processing can start.

I can look into this if there's interest, but some of the practicalities might turn out to be a bit ugly.  If you have a nice (preferbly small, and from a small genome) example CRAM file I can use to test that would help get things moving.

**Comment by FriederikeHanssen** [comment]
Awesome, thanks 😃 

GitHub does not support attachment of .cram files. Here is a small from EBI, approximately 80MB: https://www.ebi.ac.uk/ena/browser/view/ERS240640 

The download didn't work when clicking on the name directly, but by selecting the file and pressing 'Download selected files'

**Comment by s-andrews** [comment]
I had a go at implementing this and there is a basic implementation in the cram branch which should work for the test file which was specified.  At the moment I've hardcoded the reference file path but it would be easy enough to add that as an option.

Unfortuantely this fails on the test file with the following error:

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: CRAM version 2.0 is not supported
	at htsjdk.samtools.cram.build.CramIO.readCramHeader(CramIO.java:132)
	at htsjdk.samtools.cram.build.CramContainerIterator.<init>(CramContainerIterator.java:25)
	at htsjdk.samtools.CRAMIterator.<init>(CRAMIterator.java:63)
	at htsjdk.samtools.CRAMFileReader.initWithStreams(CRAMFileReader.java:200)
	at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:151)
	at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:170)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:415)
	at uk.ac.babraham.FastQC.Sequence.BAMFile.<init>(BAMFile.java:66)
```

So it looks like htsjdk don't support CRAM version 2.0, which is what that file is.  Looking into their source at: https://github.com/samtools/htsjdk/blob/e803eea9b7edb56edb773f881a0b039399e061cc/src/main/java/htsjdk/samtools/cram/common/CramVersions.java it looks like they only support versions 2.1 and 3.0.

```
    final static Set<CRAMVersion> supportedCRAMVersions = new HashSet<CRAMVersion>() {{
        add(CRAM_v2_1);
        add(CRAM_v3);
    }};
```

So although I can add the remainder of the infrastructure needed to support this, it may be that it won't work for a significant number of input files.  I've no idea what the break down between different CRAM versions is in real world data.

**Comment by s-andrews** [comment]
Got a reply from the htslib people:

> Your inquiry is only the second time in several years that I can recall someone asking about 2.0 (though the other time was two weeks ago…).

> I would think that the vast majority of cram in the wild is 3.0.

So maybe the implementation is actually good enough for what we need.  I'll try to find another test file, and then build a snapshot for people to test.  If it works out I can put this into a new release.

**Comment by Pranav-Garg** [comment]
I am trying to use the cram branch, but there are a couple of issues:

1. I believe the line for the reference option might have a mistake: `'reference=s' -> \$reference` . Replacing the `-` with an `=` removes the following error message:
```
Backslash found where operator expected at FastQC-cram/fastqc line 114, near "-> \"       
        (Missing operator before \?)
```

2. I couldn't compile the source myself. Using ant 1.9.6 gives me an error that

```
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 5
    [javac] error: Source option 5 is no longer supported. Use 7 or later.
    [javac] error: Target option 5 is no longer supported. Use 7 or later.
```

Could you please document how to compile?

**Comment by s-andrews** [comment]
The first fix looks right.  That seems like a typo.

The second is fixed on the main branch, but the CRAM branch is a long way behind that so we'd need to pull the changes from main into CRAM.  I'm on holiday for a week now so looked to see if I could do a simple merge, but it looks like that isn't going to work.  I'll see if I can find time to merge this and resolve conflicts (there shouldn't be anything nasty), but that won't be until I'm back.

For a quick fix you can edit build.xml and change:

```
    <property name="target" value="1.5"/>
    <property name="source" value="1.5"/>
```

To...

```
    <property name="target" value="11"/>
    <property name="source" value="11"/>
```

Which should allow compilation under more recent versions of java.

**Comment by Pranav-Garg** [comment]
Thanks, I'll wait for you to merge the changes. Changing "1.5" to "11" wasn't enough because:
```
[javac] FastQC/Sequence/BAMFile.java:28: error: package htsjdk.samtools does not exist
```

**Comment by s-andrews** [comment]
I've not touched the CRAM branch in a long while @Pranav-Garg  if you have fixes which would make this a usable feature then please submit a pull request and we can look at adding them.

**Comment by muffato** [comment]
Thank you.

I've taken the `cram` branch from @Pranav-Garg  . It works on a file I got from our sequencing operations team. It works on a CRAM file I've generated myself with samtools, but it fails on another file I've generated myself with samtools

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/compress/compressors/bzip2/BZip2CompressorOutputStream
        at htsjdk.samtools.cram.compression.ExternalCompressor.getCompressorForMethod(ExternalCompressor.java:81)
        at htsjdk.samtools.cram.structure.CompressorCache.lambda$getCachedCompressorForMethod$0(CompressorCache.java:94)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at htsjdk.samtools.cram.structure.CompressorCache.getCachedCompressorForMethod(CompressorCache.java:92)
        at htsjdk.samtools.cram.structure.CompressorCache.getCompressorForMethod(CompressorCache.java:64)
        at htsjdk.samtools.cram.structure.block.Block.getUncompressedContent(Block.java:230)
        at htsjdk.samtools.cram.structure.SliceBlocksReadStreams.<init>(SliceBlocksReadStreams.java:67)
        at htsjdk.samtools.cram.encoding.reader.CramRecordReader.<init>(CramRecordReader.java:89)
        at htsjdk.samtools.cram.structure.Slice.deserializeCRAMRecords(Slice.java:414)
        at htsjdk.samtools.cram.structure.Container.getSAMRecords(Container.java:320)
        at htsjdk.samtools.CRAMIterator.nextContainer(CRAMIterator.java:112)
        at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:204)
        at htsjdk.samtools.SamReader$AssertingIterator.hasNext(SamReader.java:608)
        at uk.ac.babraham.FastQC.Sequence.BAMFile.readNext(BAMFile.java:115)
        at uk.ac.babraham.FastQC.Sequence.BAMFile.<init>(BAMFile.java:75)
        at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:100)
        at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:163)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:125)
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.compressors.bzip2.BZip2CompressorOutputStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 20 more
```

I've tried:

- the `cram` branch as it is, and merging `master` into it
- upgrading various `.jar`, including `htsjdk.jar` and `commons-compress.jar` but I'm still getting that error on that CRAM file.
  I'm no expert with Java compilation and dependency management, maybe I'm missing something obvious ?

**Comment by s-andrews** [comment]
OK, I've spent some time looking at this.

The basic support for CRAM seems to be working OK, but is quite manual in that you need to manually download and index a reference which you can then pass to fastqc and it works.

What I see when using samtools is that there is no manual specification of reference.  What it's doing instead is using the MD5 signatures in the header to identify the correct reference and is automatically populating a cache directory and then using that for decompression.  This is a much better experience so we should aim to do that too.

The mechanism seems to be to use a public refget service such as the [one from the EBI](https://www.ebi.ac.uk/ena/cram/swagger-ui/index.html) to retrieve the appropriate reference.  Samtools caches these in ~/.cache/hts-ref/ so we should use that too so we can preserve previous references and pick up ones people have already used.

I'll have a go and see if I can get this to work.  It will only work for files with a compatible signature in the header, but that's likely to be quite a lot of real world CRAM files.
