### ISSUE TITLE
No known encodings with chars < 33 (Yours was  )

### ISSUE THREAD

**Issue by mvheetve** [s-andrews/FastQC#73]
Hi,

ran into the following error. I'm think there's unknown characters in the file, in this case blank spaces I'm guessing. Please advise on how to proceed. 

```
fastqc /kyukon/data/gent/vo/000/gvo00082/research/mvheetve/temp/CEP162/fastq/18-00416.fastq 
Started analysis of 18-00416.fastq
Approx 5% complete for 18-00416.fastq
Approx 10% complete for 18-00416.fastq
Approx 15% complete for 18-00416.fastq
Approx 20% complete for 18-00416.fastq
Approx 25% complete for 18-00416.fastq
Approx 30% complete for 18-00416.fastq
Approx 35% complete for 18-00416.fastq
Approx 40% complete for 18-00416.fastq
Approx 45% complete for 18-00416.fastq
Approx 50% complete for 18-00416.fastq
Approx 55% complete for 18-00416.fastq
Approx 60% complete for 18-00416.fastq
Approx 65% complete for 18-00416.fastq
Approx 70% complete for 18-00416.fastq
Approx 75% complete for 18-00416.fastq
Approx 80% complete for 18-00416.fastq
Approx 85% complete for 18-00416.fastq
Approx 90% complete for 18-00416.fastq
Approx 95% complete for 18-00416.fastq
Analysis complete for 18-00416.fastq
Failed to process file 18-00416.fastq
java.lang.IllegalArgumentException: No known encodings with chars < 33 (Yours was  )
	at uk.ac.babraham.FastQC.Sequence.QualityEncoding.PhredEncoding.getFastQEncodingOffset(PhredEncoding.java:32)
	at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.getPercentages(PerBaseQualityScores.java:71)
	at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.raisesError(PerBaseQualityScores.java:166)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:336)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:185)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:123)
	at java.base/java.lang.Thread.run(Thread.java:834)

grep " " /kyukon/data/gent/vo/000/gvo00082/research/mvheetve/temp/CEP162/fastq/18-00416.fastq | wc -l
8380
```

Regards
mvheetve

**Comment by s-andrews** [comment]
Thanks for reporting this.  The grep doesn't really tell you the root cause of the problem.  Spaces are valid characters in ID lines, so finding them in the file isn't a problem, only if they appear in a quality string.

Given that the error you got is only when the encodings are examined this means that you didn't get an immediate error when the length of the quality scores was less than the length of the read, which means you don't just have a trailing space, you have an actual space (or other nonprinting character) somewhere within the quality string, so it's probably not just a blank line at the start or end.

If you are able to share the file with me I'd be happy to take a look and see what's going on.  Just email me (simon.andrews@babraham.ac.uk) either with a location where I can download it, or if you prefer I can set up a temporary FTP site you can push it to.

**Comment by mvheetve** [comment]
Hi,

thanks for your reply. 
You are absolutely right in stating that spaces are valid characters, but looking at the ID lines in this specific file I didn't expect this. Here's a snippet:

```
head 18-00416.fastq 
@-286739763:156819336
TCATGTATTATTTCCATGAGTTGCCACTCTCACATGGGGACTTTAACCAAGAAAATGAAGGGTGTAACTAAGACTGGCTGCTAAGCAACAGCCCCACTCTGGAAGTCCCTCTTCAAGTCATTGTGACATTGATTTGTGCAAGGCAGCATT
+
AAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEEAEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEAE<A<AEEEEEEAEEE
@-286739763:4720752
CTCATGTATTATTTCCATGAGTTGCCACTCTCACATGGGGACTTTAACCAAGAAAATGAAGGGTGTAACTAAGACTGGCTGCTAAGCAACAGCCCCACTCTGGAAGTCCCTCTTCAAGTCATTGTGACATTGATTTGTGCGAGGCAGCATT
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEA<EEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEA/<AAAEEAAEE
@-286739763:177917680
CTCATGTATTATTTCCATGAGTTGCCACTCTCACATGGGGACTTTAACCAAGAAAATGAAGGGTGTAACTAAGACTGGCTGCTAAGCAACAGCCCCACTCTGGAAGTCCCTCTTCAAGTCATTGTGACATTGATTTGTGCAAGGCAGCATT
```
Upon further investigation it turns out this file contains strings of spaces (of different lengths) in some quality lines, here's an example:

```
@-1836476650:16002784
ACAAAGGAGCACTTAGTGAAATCGAGCCCATTGGTAGGGATGACACATTGCTTCCAATGGGCTGGATTTCACTAAGTGCTCCTTTGTGTTTTTCCAGAGGTTTGGGAGTTGGGTTGGTTCAAAGAGGAGAAGGAGGCTAGGT
+
**THERE WERE 142 CONSECUTIVE SPACES AT THIS LOCATION (= length of @-1836476650:16002784 sequence string)**
@-286739763:16002784
ACAAAGGAGCACTTAGTGAAATCGAGCCCATTGGTAGGGATGACACATTGCTTCCAATGGGCTGGATTTCACTAAGTGCTCCTTTGTGTTTTTCCAGAGGTTTGGGAGTTGGGTTGGTTCAAAGAGGAGAAGGAGGCTAGGT
+
EEEE6EEAEEAAAE6EEAEEEEE///E/EE///EE/EE/A/</////EE/EA/////E/EA///A/AEE////AE/<E///////A/E/E<E////<//<//A/EE///AEA<//EA////<E///<///E/<//A<E///<
```

After removing all lines containing spaces using `sed` FastQC works perfectly. To double check I wrote all instances of spaces to a new file, which turned out to be completely blank, 8380 rows with strings of spaces of various lengths. 
I'm am however quite curious to get your take on why these lines are present in the file. Fastq was generated from an alignment file. This is surely something I'd like to avoid in the future. 

Sorry for not closing this thread earlier, kinda slipped my mind. 
mvheetve

**Comment by giuliahub** [comment]
I have exactly the same issue. @mvheetve could you please share the sed command you applied?
