### ISSUE TITLE
command line run interrupted by set _JAVA_OPTIONS

### ISSUE THREAD

**Issue by brobr** [s-andrews/FastQC#77]
running FastQc as gui works fine but from command line it throws an error:
>bash-5.1$ fastqc samtoolsAligned.sortedByCoord.out.bam
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
Started analysis of samtoolsAligned.sortedByCoord.out.bam
Approx 5% complete for samtoolsAligned.sortedByCoord.out.bam
Approx 10% complete for samtoolsAligned.sortedByCoord.out.bam
Approx 15% complete for samtoolsAligned.sortedByCoord.out.bam
..
Approx 95% complete for samtoolsAligned.sortedByCoord.out.bam
Approx 100% complete for samtoolsAligned.sortedByCoord.out.bam
Analysis complete for samtoolsAligned.sortedByCoord.out.bam
Exception in thread "Thread-1" java.lang.Error: Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel
	at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1351)
	at javax.swing.UIManager.initialize(UIManager.java:1459)
	at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
	at javax.swing.UIManager.getUI(UIManager.java:1006)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at uk.ac.babraham.FastQC.Graphs.QualityBoxPlot.<init>(QualityBoxPlot.java:49)
	at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.getResultsPanel(PerBaseQualityScores.java:53)
	at uk.ac.babraham.FastQC.Modules.AbstractQCModule.writeDefaultImage(AbstractQCModule.java:62)
	at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.makeReport(PerBaseQualityScores.java:199)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:131)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:185)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:123)
	at java.lang.Thread.run(Thread.java:748)

This is on:
>bash-5.1$ java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

Turning off the extra settings (to get a nicer looking font) repairs this. (But why would this be necessary?)
>bash-5.1$ unset _JAVA_OPTIONS
bash-5.1$ echo $_JAVA_OPTIONS
>
>bash-5.1$ fastqc samtoolsAligned.sortedByCoord.out.bam
Started analysis of samtoolsAligned.sortedByCoord.out.bam
Approx 5% complete for samtoolsAligned.sortedByCoord.out.bam
Approx 10% complete for samtoolsAligned.sortedByCoord.out.bam
Approx 15% complete for samtoolsAligned.sortedByCoord.out.bam
..
Approx 95% complete for samtoolsAligned.sortedByCoord.out.bam
Approx 100% complete for samtoolsAligned.sortedByCoord.out.bam
Analysis complete for samtoolsAligned.sortedByCoord.out.bam
bash-5.1$

**Comment by s-andrews** [comment]
I just noticed that one of the changes in the latest release 0.11.9 was

"Remove linux look and feel because it's horribly broken"!

Are you using the latest release?  If not does this issue go away if you update?

**Comment by s-andrews** [comment]
As this is an issue which only occurs if someone sets non-standard java options, and since it's also an issue which picks up bugs in the java linux look and feel I don't think there's anything I can do from our side to fix this.  On a standard linux install the graphics on linux seem to be OK (it's what we use) so this is a system specific problem.

If anyone has this problem hopefully they'll find this report to help them get to the bottom of it.

**Comment by oldherl** [comment]
Hello, I'm experiencing the same issue. What's strange is that if I don't provide any command line parameters and start fastqc in GUI mode, it is working correctly with the GTK lookandfeel. It only produces error when starting in CLI mode.
