### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by KatyBrown** [s-andrews/FastQC#8]
Hi,
I am running FastQC on a large number of publicly available datasets.  For the vast majority it runs with no problem but in a few cases I get errors similar to the following and I can't figure out the cause.

```
Started analysis of SRR3138959.SRR3141013.SRR3141266_2.fastq.gz
Approx 5% complete for SRR3138959.SRR3141013.SRR3141266_1.fastq.gz
Approx 5% complete for SRR3138959.SRR3141013.SRR3141266_2.fastq.gz
Approx 10% complete for SRR3138959.SRR3141013.SRR3141266_1.fastq.gz
Approx 10% complete for SRR3138959.SRR3141013.SRR3141266_2.fastq.gz
Approx 15% complete for SRR3138959.SRR3141013.SRR3141266_1.fastq.gz
Approx 15% complete for SRR3138959.SRR3141013.SRR3141266_2.fastq.gz
Approx 20% complete for SRR3138959.SRR3141013.SRR3141266_1.fastq.gz
Approx 20% complete for SRR3138959.SRR3141013.SRR3141266_2.fastq.gz
Exception in thread "Thread-1" java.lang.ArrayIndexOutOfBoundsException: 4
        at uk.ac.babraham.FastQC.Modules.PerTileQualityScores.processSequence(PerTileQualityScores.java:210)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:88)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-2" java.lang.ArrayIndexOutOfBoundsException: 4
        at uk.ac.babraham.FastQC.Modules.PerTileQualityScores.processSequence(PerTileQualityScores.java:210)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:88)
        at java.lang.Thread.run(Thread.java:745)
```
I am running FastQC v0.11.5 in Scientific Linux on an HPC cluster.

Thanks very much,
Katy

**Comment by s-andrews** [comment]
Thanks for reporting this.

I think this is a known bug, and one that was fixed in the 0.11.6 release and affected the parsing of tile numbers from the headers of some fastq files.

Can you please try the analysis on one of the affected files with the latest release of FastQC and see if that works.  If not then add a note here giving the updated crash trace and I'll look at this.

**Comment by KatyBrown** [comment]
You're right - that fixed it!

Thanks very much.
Katy

**Comment by grendon** [comment]
I am having a similar problem with FastQC version 0.11.8 and a dataset of oxford nanopore reads

`Started analysis of 19755_PCR.qualtrim.clean.fastq.gz
Analysis complete for 19755_PCR.qualtrim.clean.fastq.gz
Failed to process file 19755_PCR.qualtrim.clean.fastq.gz
java.lang.ArrayIndexOutOfBoundsException: -1
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.calculateDis
tribution(SequenceLengthDistribution.java:101)
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.raisesError(
SequenceLengthDistribution.java:190)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLRepo
rtArchive.java:336)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchi
ve.java:84)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(Offline
Runner.java:178)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java
:110)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by s-andrews** [comment]
Moving this last comment to a new issue, as it's not related to this one (even though the crash message is similar)
