### ISSUE TITLE
crash command

### ISSUE THREAD

**Issue by estelabruxel** [s-andrews/FastQC#92]
Hello!
I am with a trouble with fastqc command:
estela@bioinf1:~/FastQC$ fastqc --help
Sorry, command-not-found has crashed! Please file a bug report at:
https://bugs.launchpad.net/command-not-found/+filebug
Please include the following information with the report:

command-not-found version: 0.3
Python version: 3.8.10 final 0
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
Exception information:

file is not a database
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/CommandNotFound/util.py", line 23, in crash_guard
    callback()
  File "/usr/lib/command-not-found", line 95, in main
    if not cnf.advise(args[0], options.ignore_installed) and not options.no_failure_msg:
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 363, in advise
    packages = self.get_packages(command)
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 97, in get_packages
    return self.db.lookup(command)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 19, in lookup
    for row in self.con.execute(
sqlite3.DatabaseError: file is not a database

Could you help me??

**Comment by s-andrews** [comment]
The error you're getting isn't coming from fastqc, but from another program you have installed which tries to make sensible suggestions if you try to run a program which can't be located on your system.

The FastQC problem in this is that fastqc isn't being found on your system, so either it's not installed at all, or it's installed somewhere but hasn't been added to your PATH variable which says where the system will look for programs when they're specified by name.

If you've not installed it at all then go to:

https://www.bioinformatics.babraham.ac.uk/projects/download.html#fastqc

..to grab a copy and follow the install instructions.

Assuming that you've already done this and that fastqc is installed in your home directory (```/home/estela/FastQC```) then you have a couple of choices:

1. You can just call fastqc explicitly rather than by using the PATH, this would mean that instead of running ```fastqc``` you'd run ```/home/estla/FastQC/fastqc``` so the system doesn't have to search for it.
2. You could add a link to fastqc to a folder which is already in your PATH, such as ```/usr/local/bin```, to do that you'd run ```sudo ln -s /home/estela/FastQC/fastqc /usr/local/bin/fastqc```.
3. You modify your PATH to add the FastQC folder to the list of locations to search. To do this you'd edit the ```.bashrc``` file in your home directory and would add a line which said ```export PATH=/home/estela/FastQC/fastqc:$PATH```

Either of 2 or 3 would mean that you could now run FastQC from anywhere by just running ```fastqc```.  Please also note that installing FastQC involves making the launch script executable (this is in the install instructions) which in your case would, just once, mean running ```chmod 755 /home/estela/FastQC/fastqc```

Hopefully this should get you up and running.
