### ISSUE TITLE
another "Headless exception" problem

### ISSUE THREAD

**Issue by dsb66** [s-andrews/FastQC#98]
I am trying to run FastQC in interactive mode on a remote RedHat server that runs the standard Gnome desktop. Session and error message:

`(base) FastQC$ ./fastqc 
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at uk.ac.babraham.FastQC.FastQCApplication.<init>(FastQCApplication.java:63)
	at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:338)
`
This used to work on remote Ubuntu desktop. I am connecting to the RedHat server through a tunneled VNC connection. I don't want to do X11 forwarding and would prefer using the graphical interface. Please advise, thanks.

**Comment by s-andrews** [comment]
If you're on a VNC desktop then it should just work - we run all of our training desktops this way without issue.  That error suggests that something isn't right in your connection as it's not finding a display to connect to, which would either be X to a VNC desktop, or an X tunnel back to a local X server.  I'm guessing this problem would affect all graphical applications, not just fastqc so it's not really an issue with the setup of this program.

Without more details of how you've set up your connection I can't really suggest how to debug this, but there's certainly nothing within the program which would prevent this from working and we know that a similar setup works just fine on other systems so this should work.
